fedora:
    variables:
        LAST_ABI_BREAK: 87e278ef077b4952595cf9d6e973e6d8246f20b3
    image:
        name: registry.gitlab.gnome.org/gnome/gnome-autoar:latest
        entrypoint: ["/bin/sh", "-c"]
    script:
        - meson setup _build --prefix=/usr -Dgtk_doc=false -Dintrospection=enabled -Dtests=true
        - ninja -C _build test
        - check-abi $LAST_ABI_BREAK $(git rev-parse HEAD)
pages:
    image: registry.gitlab.gnome.org/gnome/gnome-autoar:latest
    stage: deploy
    rules:
        # https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == "GNOME"
    script:
        - meson setup -Dgtk_doc=true -Dtests=false _build
        - ninja -C _build
        - mv _build/docs/reference/gnome-autoar/ public/
    artifacts:
        paths:
            - public/
        expire_in: 2 days
update image:
    variables:
         STORAGE_DRIVER: vfs
         BUILDAH_FORMAT: docker
         BUILDAH_ISOLATION: chroot
    image: registry.fedoraproject.org/fedora:latest
    script:
        - dnf install -y buildah runc
        - buildah --storage-driver=vfs bud --tag $CI_REGISTRY_IMAGE -f .gitlab/Dockerfile
        - buildah tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - buildah push --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
        - buildah push --creds $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
    when: manual
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "GNOME"
